// Code generated by mockery. DO NOT EDIT.

package core_mock

import mock "github.com/stretchr/testify/mock"

// CmdError is an autogenerated mock type for the ICmdError type
type CmdError struct {
	mock.Mock
}

type CmdError_Expecter struct {
	mock *mock.Mock
}

func (_m *CmdError) EXPECT() *CmdError_Expecter {
	return &CmdError_Expecter{mock: &_m.Mock}
}

// ExitCode provides a mock function with given fields:
func (_m *CmdError) ExitCode() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExitCode")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// CmdError_ExitCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExitCode'
type CmdError_ExitCode_Call struct {
	*mock.Call
}

// ExitCode is a helper method to define mock.On call
func (_e *CmdError_Expecter) ExitCode() *CmdError_ExitCode_Call {
	return &CmdError_ExitCode_Call{Call: _e.mock.On("ExitCode")}
}

func (_c *CmdError_ExitCode_Call) Run(run func()) *CmdError_ExitCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CmdError_ExitCode_Call) Return(code int) *CmdError_ExitCode_Call {
	_c.Call.Return(code)
	return _c
}

func (_c *CmdError_ExitCode_Call) RunAndReturn(run func() int) *CmdError_ExitCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewCmdError creates a new instance of CmdError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCmdError(t interface {
	mock.TestingT
	Cleanup(func())
}) *CmdError {
	mock := &CmdError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
